# Generated by Django 5.0.6 on 2024-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_created_at_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(default='None for now', max_length=255),
        ),
    ]
