# Generated by Django 5.0.6 on 2024-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
